/**
 * Interface ContactMessage
 *
 * This interface represents a ContactMessage as generated by the API. It has the equivalent properties of
 * drogon_model::sqlite3::ContactMessages in the server side.
 *
 * @author Carlos Amores
 */
export default interface ContactMessage
{
    id : number;
    name : string;
    surname : string;
    email : string;
    message : string;
    hash : string;
    submission_ts : number
}
